alias shutdown='sudo shutdown -h now'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias less='less --quiet'
alias h='cd ~'
alias b='acpi -b'
alias df='df --human-readable'
alias du='cdu -idh'
alias free='free -h'
alias x='startx'
#alias gitmaster='git push -u origin master && echo " (╯°□°）╯︵ WTF DID YOU PUSH BRO?"'
alias grep='grep --color=auto'
alias pacman='sudo pacman'
alias dmesg='dmesg -H'
#alias pacup='pacman -Syu'
#alias pacrm='pacman -Rdd'
alias paclog='tail -n 40 /var/log/pacman.log'
alias svim='sudo vim'
alias mplayer='mplayer -msgcolor -msgmodule'
alias :q='exit'
alias rmnotneed='pacman -Rscn $(pacman -Qdtq)'
alias pacorphans="pacman -Qtdq > /dev/null && sudo pacman -Rns \$(pacman -Qtdq | sed -e ':a;N;$!ba;s/\n/ /g')"
alias update="pacman -Syy && pacman -Su"
alias p3="python 3"
alias p2="python 2"
alias pwm="ping -c 2 www.mschettini.me"
alias nvstatus="cat /proc/acpi/bbswitch"
alias nvon="sudo tee /proc/acpi/bbswitch <<<ON"
alias nvoff="sudo tee /proc/acpi/bbswitch <<<OFF"
alias photo="fswebcam -r 640x480 -F 10 -s brightness=80%"
alias ydl="youtube-dl -x"
alias napsterssh="ssh -p 1957 napster@178.62.201.48"
